# -*- coding: utf-8 -*-
"""setup

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16sCTtb8EOXH4K-NralhpujPPkoSUSoNm
"""

#!/usr/bin/env python
from distutils.core import setup

setup(
    name='-Quiz_Game---DEWILDE_Chloe---DIA6-',
    version='1.0',
    author='Chloedw1302',
    license='MIT',
    long_description=open('README.md').read(),
)